traido desde el repo central

diff --git a/files/etc/init.d/emad b/files/etc/init.d/emad
--- a/files/etc/init.d/emad
+++ b/files/etc/init.d/emad
@@ -36,6 +36,14 @@ CONFIG_FILE=/etc/$NAME/config
 # and status_of_proc is working.
 . /lib/lsb/init-functions
 
+# Override verbose value to work with systemd
+VERBOSE=yes
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
 DAEMON_ARGS="-m $NAME --config $CONFIG_FILE"
 
 #
@@ -43,14 +51,6 @@ DAEMON_ARGS="-m $NAME --config $CONFIG_FILE"
 #
 do_start()
 {
-    local poweroff=$1
-    if [ "$poweroff" = "alive" ]
-    then
-		POWEROFF=""
-    else
-		POWEROFF=" --poweroff"
-    fi
-    DAEMON_ARGS="${DAEMON_ARGS}${POWEROFF}"
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
@@ -63,6 +63,7 @@ do_start()
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
 	# on this one.  As a last resort, sleep for some time.
+	return 0
 }
 
 #
@@ -126,7 +127,7 @@ do_resume() {
 case "$1" in
     start)
 	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start "$2"
+	do_start
 	case "$?" in
 	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
 	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
@@ -148,49 +149,47 @@ case "$1" in
 	# If do_reload() is not implemented then leave this commented out
 	# and leave 'force-reload' as an alias for 'restart'.
 	#
-	log_daemon_msg "Reloading $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC" "$NAME"
 	do_reload
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_end_msg $?
 	;;
     pause)
-	log_daemon_msg "Pausing $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Pausing $DESC" "$NAME"
 	do_pause
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_end_msg $?
 	;;
     resume)
 	#
 	# If do_pause() is not implemented then leave this commented out
 	#
-	log_daemon_msg "Resume $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Resume $DESC" "$NAME"
 	do_resume
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_end_msg $?
 	;;
     restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
 	    0|1)
-		do_start "$2"
+		do_start
 		case "$?" in
-		    0) log_end_msg 0 ;;
-		    1) log_end_msg 1 ;; # Old process is still running
-		    *) log_end_msg 1 ;; # Failed to start
+		    0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		    1) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Old process is still running
+		    *) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Failed to start
 		esac
 		;;
 	    *)
 		# Failed to stop
-		log_end_msg 1
+		[ "$VERBOSE" != no ] && log_end_msg 1
 		;;
 	esac
 	;;
     *)
-	echo "Usage: $SCRIPTNAME {start [alive]|stop|restart [alive]|reload|force-reload|pause|resume}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload|pause|resume}" >&2
 	exit 3
 	;;
 esac
-
-
